Document: qgroundcontrol
Title: Debian qgroundcontrol Manual
Author: <insert document author here>
Abstract: This manual describes what qgroundcontrol is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qgroundcontrol/qgroundcontrol.sgml.gz

Format: postscript
Files: /usr/share/doc/qgroundcontrol/qgroundcontrol.ps.gz

Format: text
Files: /usr/share/doc/qgroundcontrol/qgroundcontrol.text.gz

Format: HTML
Index: /usr/share/doc/qgroundcontrol/html/index.html
Files: /usr/share/doc/qgroundcontrol/html/*.html
